import { Trip } from './types';

export const allTrips: Trip[] = [
  { id: "16", title: "JAIPUR PINK CITY BLITZ", days: 4, desc: "Forts, bazaars, rooftop sunsets, and laal maas that bites back.", handle: "@desi_roamer", avatarInit: "DR", imageUrl: "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1200&q=80", isHot: true, vibe: "Culture & Art", curator: { handle: "@desi_roamer", avatar: "" } },
  { id: "17", title: "GOA BEACH RESET", days: 5, desc: "Shacks, flea markets, scooter rides, and late-night beach bass.", handle: "@konkan_kid", avatarInit: "KK", imageUrl: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1200&q=80", isHot: true, vibe: "Party", curator: { handle: "@konkan_kid", avatar: "" } },
  { id: "18", title: "KERALA BACKWATER SLOWDOWN", days: 6, desc: "Houseboats, coconut curries, spice gardens, and monsoon-green calm.", handle: "@malabar_miles", avatarInit: "MM", imageUrl: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=1200&q=80", isHot: false, vibe: "Chill / Relax", curator: { handle: "@malabar_miles", avatar: "" } },
  { id: "19", title: "VARANASI DAWN RITUALS", days: 3, desc: "Ghats, temple bells, boat rides, and old lanes humming before sunrise.", handle: "@ganga_walks", avatarInit: "GW", imageUrl: "https://images.unsplash.com/photo-1561361058-c24cecae35ca?auto=format&fit=crop&w=1200&q=80", isHot: false, vibe: "Culture & Art", curator: { handle: "@ganga_walks", avatar: "" } },
  { id: "20", title: "LADAKH HIGH-ALTITUDE LOOP", days: 9, desc: "Blue lakes, brutal passes, prayer flags, and thin-air road drama.", handle: "@himalaya_mode", avatarInit: "HM", imageUrl: "https://images.unsplash.com/photo-1581793745862-99fde7fa73d2?auto=format&fit=crop&w=1200&q=80", isHot: true, vibe: "Backpacker", curator: { handle: "@himalaya_mode", avatar: "" } },
  { id: "21", title: "MUMBAI FOOD RUN", days: 4, desc: "Vada pav, Irani cafes, sea-facing walks, and midnight kebab missions.", handle: "@bombay_bites", avatarInit: "BB", imageUrl: "https://images.unsplash.com/photo-1566552881560-0be862a7c445?auto=format&fit=crop&w=1200&q=80", isHot: false, vibe: "Foodie", curator: { handle: "@bombay_bites", avatar: "" } },
  { id: "22", title: "MARRAKECH MEDINA MAZE", days: 5, desc: "Riads, spice stalls, desert colors, and mint tea between souks.", handle: "@atlas_wander", avatarInit: "AW", imageUrl: "https://images.unsplash.com/photo-1548018560-c7196548e84d?auto=format&fit=crop&w=1200&q=80", isHot: false, vibe: "Culture & Art", curator: { handle: "@atlas_wander", avatar: "" } },
  { id: "23", title: "CAPE TOWN COAST DRIVE", days: 7, desc: "Table Mountain, penguin beaches, wine valleys, and ocean roads.", handle: "@cape_cruise", avatarInit: "CC", imageUrl: "https://images.unsplash.com/photo-1580060839134-75a5edca2e99?auto=format&fit=crop&w=1200&q=80", isHot: false, vibe: "Chill / Relax", curator: { handle: "@cape_cruise", avatar: "" } },
  { id: "24", title: "ISTANBUL TWO-CONTINENT FEAST", days: 5, desc: "Ferries, hammams, baklava, and skyline calls to prayer.", handle: "@bosphorus_bites", avatarInit: "BB", imageUrl: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?auto=format&fit=crop&w=1200&q=80", isHot: true, vibe: "Foodie", curator: { handle: "@bosphorus_bites", avatar: "" } },
  { id: "25", title: "LISBON TILE HUNT", days: 4, desc: "Trams, miradouros, tiled alleys, and custard tart detours.", handle: "@azulejo_days", avatarInit: "AD", imageUrl: "https://images.unsplash.com/photo-1513735492246-483525079686?auto=format&fit=crop&w=1200&q=80", isHot: false, vibe: "Culture & Art", curator: { handle: "@azulejo_days", avatar: "" } },
  { id: "26", title: "DUBAI SKYLIFE WEEKEND", days: 3, desc: "Skyline flex, desert dune runs, beach clubs, and gold souks.", handle: "@dune_signal", avatarInit: "DS", imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80", isHot: false, vibe: "Luxury", curator: { handle: "@dune_signal", avatar: "" } },
  { id: "27", title: "HANOI SCOOTER SUPPER", days: 5, desc: "Pho steam, train street buzz, egg coffee, and lake loops.", handle: "@pho_runner", avatarInit: "PR", imageUrl: "https://images.unsplash.com/photo-1509030450996-dd1a26dda07a?auto=format&fit=crop&w=1200&q=80", isHot: false, vibe: "Foodie", curator: { handle: "@pho_runner", avatar: "" } },
  { id: "28", title: "QUEENSTOWN ADRENALINE MAP", days: 8, desc: "Bungee jumps, alpine roads, lake views, and cold-air chaos.", handle: "@fjord_fever", avatarInit: "FF", imageUrl: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=1200&q=80", isHot: false, vibe: "Backpacker", curator: { handle: "@fjord_fever", avatar: "" } },
  { id: "29", title: "ATHENS ISLAND STARTER", days: 6, desc: "Ancient ruins, street souvlaki, ferry plans, and sunset steps.", handle: "@aegean_noise", avatarInit: "AN", imageUrl: "https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&w=1200&q=80", isHot: false, vibe: "Culture & Art", curator: { handle: "@aegean_noise", avatar: "" } },
  { id: "30", title: "RIO CARNIVAL CURRENT", days: 7, desc: "Beach mornings, samba nights, hilltop views, and color everywhere.", handle: "@samba_signal", avatarInit: "SS", imageUrl: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=1200&q=80", isHot: true, vibe: "Party", curator: { handle: "@samba_signal", avatar: "" } },
  { id: "1", title: "TOKYO NIGHTS & RAMEN BITES", days: 5, desc: "Neon signs, underground clubs, and the best late-night noodles.", handle: "@nomad_dude", avatarInit: "ND", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuB0FhCM0zGuxXO7QrKUVKsHGRDzYiTVx4pmW6-PyvkTr1gQnapMVg8yA3S70b7kcA6hjVjVh8j9tKPHC_LeE3zqg_VqwgeKX_A7o7_D4a2S-XyypVRQbmuaEoINtDR6_n3KsgEa6oPuXptrt5L5OTINqAGn2RVAgqkwVduG_fbVfb2QiaekH6IAIOD8ZYXQxgomCJbcDgne6Ce4FcghqvXXlemgJwvRG6CgWzCipQSHYqDRvQMXaAY5DNg7LfyTQ9KR08urrkyYpL0", isHot: true, vibe: "Party", curator: { handle: "@nomad_dude", avatar: "" } },
  { id: "2", title: "BALI CHAOS ESCAPE", days: 14, desc: "Scooters, surf breaks, and avoiding the influencers in Canggu.", handle: "@sarah_jumps", avatarInit: "SJ", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAaWzeRO9Il6rumrhgn1XZmJQgaoIJBTU-FbkvjS_zqy2M6Y91Rw_ALoYtRuc14E8xY4C42WN2dbx9uDcZ7wzws1BEbl5si4KbH65At42Rd1EW_uqTDcsQ7CbYJ9ZNNpA8QY7McuBX0wyB5NaF9QwFNtaXBtpuWYyfmeARWSqvjyDzyjB3Wz2aNYLe4AmZgceb_p0ILZeHgyuNmP4iU-AAYsLUhLyFfG0MfcWpuictskLVBNtht0iwccGuMjvqDh0ayFDhQRaahHvU", isHot: false, vibe: "Backpacker", curator: { handle: "@sarah_jumps", avatar: "" } },
  { id: "3", title: "PARIS ON A DIME", days: 3, desc: "Cheap wine, street art, and walking until your feet bleed.", handle: "@broke_explorer", avatarInit: "BX", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDp8kBJ7hhv4aB9Px9t06RVIg2QRHv7fgoooLdKnnBbKHnk7pnIdoi_nZktvt2cVBTjRpNYCreqKu9EsWfBeNcYvl1TXhttVxZdMxRVqQ3RFl4D4Cx5i5QQfW44t_XZOcMDJIiockoFx8Old48unVqn72WPEim1Hp2pAGU28OnFHf3pXFs6F5o4WB1teVjAvKYnhmhNyrMld8M5Og_M-p4SYF2gW7n9X4kH7kJF5JuozNZnmxcD5ugfSXhBReP1fMQqYvQmx-alRog", isHot: false, vibe: "Backpacker", curator: { handle: "@broke_explorer", avatar: "" } },
  { id: "4", title: "PNW VANLIFE", days: 7, desc: "Rain, mud, and sleeping in a converted Transit van.", handle: "@van_dog", avatarInit: "VD", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAmcReLZaaNwaWJNDB9V9Fo_Tsg_oWeH7GI_dGhaWCceuV3UEBBHiuY24mRsEhSoFnBAqkZlAj5wcJGUSKoKAaoTcdRjOtEfRiq4g2v1r7IwH5nLqPzcMajeadgYeJnOofdLI9SXeKXk9kB4Z1u3I3Qyz-nf1CuHbknnM9cUhAWyZ_DXBRdCI84il3yOv4TmrhCGPNa1iZuDIZndNgvYAcIUWrLEofkQKMOx5siT9SbHVgam3GumNk2k_5gOjeD-sLeym2XcNSV9uM", isHot: false, vibe: "Chill / Relax", curator: { handle: "@van_dog", avatar: "" } },
  { id: "5", title: "ICELAND RING ROAD", days: 8, desc: "Waterfalls, glaciers, and 24-hour sunlight.", handle: "@arctic_fox", avatarInit: "AF", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuB0FhCM0zGuxXO7QrKUVKsHGRDzYiTVx4pmW6-PyvkTr1gQnapMVg8yA3S70b7kcA6hjVjVh8j9tKPHC_LeE3zqg_VqwgeKX_A7o7_D4a2S-XyypVRQbmuaEoINtDR6_n3KsgEa6oPuXptrt5L5OTINqAGn2RVAgqkwVduG_fbVfb2QiaekH6IAIOD8ZYXQxgomCJbcDgne6Ce4FcghqvXXlemgJwvRG6CgWzCipQSHYqDRvQMXaAY5DNg7LfyTQ9KR08urrkyYpL0", isHot: false, vibe: "Culture & Art", curator: { handle: "@arctic_fox", avatar: "" } },
  { id: "6", title: "SEOUL STREET FOOD", days: 4, desc: "Tteokbokki, neon lights, and soju tents.", handle: "@kimchi_lover", avatarInit: "KL", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAaWzeRO9Il6rumrhgn1XZmJQgaoIJBTU-FbkvjS_zqy2M6Y91Rw_ALoYtRuc14E8xY4C42WN2dbx9uDcZ7wzws1BEbl5si4KbH65At42Rd1EW_uqTDcsQ7CbYJ9ZNNpA8QY7McuBX0wyB5NaF9QwFNtaXBtpuWYyfmeARWSqvjyDzyjB3Wz2aNYLe4AmZgceb_p0ILZeHgyuNmP4iU-AAYsLUhLyFfG0MfcWpuictskLVBNtht0iwccGuMjvqDh0ayFDhQRaahHvU", isHot: false, vibe: "Foodie", curator: { handle: "@kimchi_lover", avatar: "" } },
  { id: "7", title: "PATAGONIA TREK", days: 14, desc: "Wind, peaks, and untouched wilderness.", handle: "@mountain_goat", avatarInit: "MG", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDp8kBJ7hhv4aB9Px9t06RVIg2QRHv7fgoooLdKnnBbKHnk7pnIdoi_nZktvt2cVBTjRpNYCreqKu9EsWfBeNcYvl1TXhttVxZdMxRVqQ3RFl4D4Cx5i5QQfW44t_XZOcMDJIiockoFx8Old48unVqn72WPEim1Hp2pAGU28OnFHf3pXFs6F5o4WB1teVjAvKYnhmhNyrMld8M5Og_M-p4SYF2gW7n9X4kH7kJF5JuozNZnmxcD5ugfSXhBReP1fMQqYvQmx-alRog", isHot: false, vibe: "Backpacker", curator: { handle: "@mountain_goat", avatar: "" } },
  { id: "8", title: "NEW YORK CITY GRIND", days: 5, desc: "Bodegas, subways, and endless hustle.", handle: "@concrete_jungle", avatarInit: "CJ", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAmcReLZaaNwaWJNDB9V9Fo_Tsg_oWeH7GI_dGhaWCceuV3UEBBHiuY24mRsEhSoFnBAqkZlAj5wcJGUSKoKAaoTcdRjOtEfRiq4g2v1r7IwH5nLqPzcMajeadgYeJnOofdLI9SXeKXk9kB4Z1u3I3Qyz-nf1CuHbknnM9cUhAWyZ_DXBRdCI84il3yOv4TmrhCGPNa1iZuDIZndNgvYAcIUWrLEofkQKMOx5siT9SbHVgam3GumNk2k_5gOjeD-sLeym2XcNSV9uM", isHot: false, vibe: "Party", curator: { handle: "@concrete_jungle", avatar: "" } },
  { id: "9", title: "AMSTERDAM CANALS", days: 3, desc: "Bikes, bridges, and hazy coffee shops.", handle: "@dutch_cyclist", avatarInit: "DC", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuB0FhCM0zGuxXO7QrKUVKsHGRDzYiTVx4pmW6-PyvkTr1gQnapMVg8yA3S70b7kcA6hjVjVh8j9tKPHC_LeE3zqg_VqwgeKX_A7o7_D4a2S-XyypVRQbmuaEoINtDR6_n3KsgEa6oPuXptrt5L5OTINqAGn2RVAgqkwVduG_fbVfb2QiaekH6IAIOD8ZYXQxgomCJbcDgne6Ce4FcghqvXXlemgJwvRG6CgWzCipQSHYqDRvQMXaAY5DNg7LfyTQ9KR08urrkyYpL0", isHot: false, vibe: "Chill / Relax", curator: { handle: "@dutch_cyclist", avatar: "" } },
  { id: "10", title: "KYOTO TEMPLES", days: 6, desc: "Bamboo forests, shrines, and matcha.", handle: "@zen_master", avatarInit: "ZM", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAaWzeRO9Il6rumrhgn1XZmJQgaoIJBTU-FbkvjS_zqy2M6Y91Rw_ALoYtRuc14E8xY4C42WN2dbx9uDcZ7wzws1BEbl5si4KbH65At42Rd1EW_uqTDcsQ7CbYJ9ZNNpA8QY7McuBX0wyB5NaF9QwFNtaXBtpuWYyfmeARWSqvjyDzyjB3Wz2aNYLe4AmZgceb_p0ILZeHgyuNmP4iU-AAYsLUhLyFfG0MfcWpuictskLVBNtht0iwccGuMjvqDh0ayFDhQRaahHvU", isHot: false, vibe: "Culture & Art", curator: { handle: "@zen_master", avatar: "" } },
  { id: "11", title: "ROME PIZZA TOUR", days: 4, desc: "Ruins, gelato, and authentic carbonara.", handle: "@pasta_king", avatarInit: "PK", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDp8kBJ7hhv4aB9Px9t06RVIg2QRHv7fgoooLdKnnBbKHnk7pnIdoi_nZktvt2cVBTjRpNYCreqKu9EsWfBeNcYvl1TXhttVxZdMxRVqQ3RFl4D4Cx5i5QQfW44t_XZOcMDJIiockoFx8Old48unVqn72WPEim1Hp2pAGU28OnFHf3pXFs6F5o4WB1teVjAvKYnhmhNyrMld8M5Og_M-p4SYF2gW7n9X4kH7kJF5JuozNZnmxcD5ugfSXhBReP1fMQqYvQmx-alRog", isHot: false, vibe: "Foodie", curator: { handle: "@pasta_king", avatar: "" } },
  { id: "12", title: "MEXICAN RIVIERA", days: 7, desc: "Cenotes, tacos, and massive surf breaks.", handle: "@taco_queen", avatarInit: "TQ", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAmcReLZaaNwaWJNDB9V9Fo_Tsg_oWeH7GI_dGhaWCceuV3UEBBHiuY24mRsEhSoFnBAqkZlAj5wcJGUSKoKAaoTcdRjOtEfRiq4g2v1r7IwH5nLqPzcMajeadgYeJnOofdLI9SXeKXk9kB4Z1u3I3Qyz-nf1CuHbknnM9cUhAWyZ_DXBRdCI84il3yOv4TmrhCGPNa1iZuDIZndNgvYAcIUWrLEofkQKMOx5siT9SbHVgam3GumNk2k_5gOjeD-sLeym2XcNSV9uM", isHot: false, vibe: "Luxury", curator: { handle: "@taco_queen", avatar: "" } },
  { id: "13", title: "THAI ISLAND HOPPING", days: 12, desc: "Longtails, buckets, and full moons.", handle: "@beach_bum", avatarInit: "BB", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuB0FhCM0zGuxXO7QrKUVKsHGRDzYiTVx4pmW6-PyvkTr1gQnapMVg8yA3S70b7kcA6hjVjVh8j9tKPHC_LeE3zqg_VqwgeKX_A7o7_D4a2S-XyypVRQbmuaEoINtDR6_n3KsgEa6oPuXptrt5L5OTINqAGn2RVAgqkwVduG_fbVfb2QiaekH6IAIOD8ZYXQxgomCJbcDgne6Ce4FcghqvXXlemgJwvRG6CgWzCipQSHYqDRvQMXaAY5DNg7LfyTQ9KR08urrkyYpL0", isHot: false, vibe: "Party", curator: { handle: "@beach_bum", avatar: "" } },
  { id: "14", title: "PERU MACHU PICCHU", days: 9, desc: "Inca trails, altitude, and llamas.", handle: "@inca_trail", avatarInit: "IT", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuAaWzeRO9Il6rumrhgn1XZmJQgaoIJBTU-FbkvjS_zqy2M6Y91Rw_ALoYtRuc14E8xY4C42WN2dbx9uDcZ7wzws1BEbl5si4KbH65At42Rd1EW_uqTDcsQ7CbYJ9ZNNpA8QY7McuBX0wyB5NaF9QwFNtaXBtpuWYyfmeARWSqvjyDzyjB3Wz2aNYLe4AmZgceb_p0ILZeHgyuNmP4iU-AAYsLUhLyFfG0MfcWpuictskLVBNtht0iwccGuMjvqDh0ayFDhQRaahHvU", isHot: false, vibe: "Backpacker", curator: { handle: "@inca_trail", avatar: "" } },
  { id: "15", title: "BERLIN TECHNOPARTY", days: 3, desc: "Bouncers, bass, and no cameras allowed.", handle: "@techno_viking", avatarInit: "TV", imageUrl: "https://lh3.googleusercontent.com/aida-public/AB6AXuDp8kBJ7hhv4aB9Px9t06RVIg2QRHv7fgoooLdKnnBbKHnk7pnIdoi_nZktvt2cVBTjRpNYCreqKu9EsWfBeNcYvl1TXhttVxZdMxRVqQ3RFl4D4Cx5i5QQfW44t_XZOcMDJIiockoFx8Old48unVqn72WPEim1Hp2pAGU28OnFHf3pXFs6F5o4WB1teVjAvKYnhmhNyrMld8M5Og_M-p4SYF2gW7n9X4kH7kJF5JuozNZnmxcD5ugfSXhBReP1fMQqYvQmx-alRog", isHot: false, vibe: "Party", curator: { handle: "@techno_viking", avatar: "" } }
];

export async function getTripById(id: string): Promise<Trip | undefined> {
  // Simulate network delay
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(allTrips.find(t => t.id === id));
    }, 10);
  });
}
